name: Main workflow

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        extensions: mbstring, curl, dom, xml, zip, sqlite
        tools: prestissimo
        php-version: '7.4'

    - name: Setup project
      run: make setup

    - name: Check lint
      run: make lint

    - name: Static analysis
      run: make analyse

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: make test-coverage

    - name: Execute tests with PostgreSQL
      run: make test
      env:
        DB_CONNECTION: pgsql
        DB_HOST: localhost
        DB_DATABASE: postgres
        DB_USERNAME: postgres
        DB_PASSWORD: postgres

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./build/logs/clover.xml
        fail_ci_if_error: true

    - name: PHP Security Checker
      uses: symfonycorp/security-checker-action@v2
